### ISSUE TITLE
Getting error while creating a client

### ISSUE THREAD

**Issue by shankarigr** [SAP/cf-java-client-sap#151]
Hi,

Currently I am using 1.25.1 version of cf-java-client library.
As specified in the readme, I couldnt find any class called CloudfoundryClient.

So when i use the below code for client creation, I am getting an error:
       _CloudCredentials credentials = new CloudCredentials("XXX" , "XXX");
       CloudControllerClient client = new 
       CloudControllerClientImpl(getTargetUrl("https://XXX.XXXcom"), credentials);
       client.login();_

Please find below the stacktrace of the exception:
_ERR Caused by: java.lang.NoClassDefFoundError: org/springframework/core/log/LogDelegateFactory
   2020-05-11T13:13:48.06+0530 [APP/PROC/WEB/0] ERR     at org.springframework.http.HttpLogging.forLog(HttpLogging.java:68)
   2020-05-11T13:13:48.06+0530 [APP/PROC/WEB/0] ERR     at org.springframework.http.HttpLogging.forLogName(HttpLogging.java:57)
   2020-05-11T13:13:48.06+0530 [APP/PROC/WEB/0] ERR     at org.springframework.http.client.support.HttpAccessor.<init>(HttpAccessor.java:54)
   2020-05-11T13:13:48.06+0530 [APP/PROC/WEB/0] ERR     at org.springframework.http.client.support.InterceptingHttpAccessor.<init>(InterceptingHttpAccessor.java:44)
   2020-05-11T13:13:48.06+0530 [APP/PROC/WEB/0] ERR     at org.springframework.web.client.RestTemplate.<init>(RestTemplate.java:137)
   2020-05-11T13:13:48.06+0530 [APP/PROC/WEB/0] ERR     at org.cloudfoundry.client.lib.rest.LoggingRestTemplate.<init>(LoggingRestTemplate.java:39)
   2020-05-11T13:13:48.06+0530 [APP/PROC/WEB/0] ERR     at org.cloudfoundry.client.lib.util.RestUtil.createRestTemplate(RestUtil.java:88)
   2020-05-11T13:13:48.06+0530 [APP/PROC/WEB/0] ERR     at org.cloudfoundry.client.lib.rest.CloudControllerRestClientFactory.getGeneralPurposeRestTemplate(CloudControllerRestClientFactory.java:81)
   2020-05-11T13:13:48.06+0530 [APP/PROC/WEB/0] ERR     at org.cloudfoundry.client.lib.rest.CloudControllerRestClientFactory.getInfoMap(CloudControllerRestClientFactory.java:146)
   2020-05-11T13:13:48.06+0530 [APP/PROC/WEB/0] ERR     at org.cloudfoundry.client.lib.rest.CloudControllerRestClientFactory.createOAuthClient(CloudControllerRestClientFactory.java:120)
   2020-05-11T13:13:48.06+0530 [APP/PROC/WEB/0] ERR     at org.cloudfoundry.client.lib.rest.CloudControllerRestClientFactory.createClient(CloudControllerRestClientFactory.java:107)
   2020-05-11T13:13:48.06+0530 [APP/PROC/WEB/0] ERR     at org.cloudfoundry.client.lib.CloudControllerClientImpl.<init>(CloudControllerClientImpl.java:139)
   2020-05-11T13:13:48.06+0530 [APP/PROC/WEB/0] ERR     at org.cloudfoundry.client.lib.CloudControllerClientImpl.<init>(CloudControllerClientImpl.java:99)_

Not sure what i am missing here.
Please help me with the same.

Thanks and Regards,
Shankari G R

**Comment by theghost5800** [comment]
Hi @shankarigr ,

This project is not exact cf-java-client provided by cloudfoundry community. We are using this project as facade of real [cf-java-client](https://github.com/cloudfoundry/cf-java-client). As I can see from exception stacktrace there is missing spring dependency spring-core, you can try to add in your pom.xml the following dependency:
```
<dependency>
     <groupId>org.springframework</groupId>
     <artifactId>spring-core</artifactId>
</dependency>
```

**Comment by nictas** [comment]
Hi @shankarigr,

I'd recommend using https://github.com/cloudfoundry/cf-java-client instead of this project, as it's more up to date, has a stable API and a broader community. This project is actually a facade that hides the newest version of https://github.com/cloudfoundry/cf-java-client behind an old interface (version 1.14), so that it can be consumed more easily in https://github.com/cloudfoundry-incubator/multiapps-controller.
