### ISSUE TITLE
Unable to get application without specifying organization and space to use.

### ISSUE THREAD

**Issue by vah13** [SAP/cf-java-client-sap#278]
Hello, I'd like to use the sample code from the readme, but I got an issue. Could you help me how I can specify the organization and/or space to use?
```
Applications:
Exception in thread "main" java.lang.IllegalArgumentException: Unable to get application without specifying organization and space to use.
	at org.springframework.util.Assert.notNull(Assert.java:201)
	at com.sap.cloudfoundry.client.facade.rest.CloudControllerRestClientImpl.assertSpaceProvided(CloudControllerRestClientImpl.java:1940)
	at com.sap.cloudfoundry.client.facade.rest.CloudControllerRestClientImpl.getApplicationResources(CloudControllerRestClientImpl.java:1665)
	at com.sap.cloudfoundry.client.facade.rest.CloudControllerRestClientImpl.fetchFlux(CloudControllerRestClientImpl.java:2730)
	at com.sap.cloudfoundry.client.facade.rest.CloudControllerRestClientImpl.fetchList(CloudControllerRestClientImpl.java:2725)
	at com.sap.cloudfoundry.client.facade.rest.CloudControllerRestClientImpl.getApplications(CloudControllerRestClientImpl.java:782)
	at com.sap.cloudfoundry.client.facade.CloudControllerClientImpl.lambda$getApplications$35(CloudControllerClientImpl.java:265)
	at com.sap.cloudfoundry.client.facade.CloudControllerClientImpl.handleExceptions(CloudControllerClientImpl.java:722)
	at com.sap.cloudfoundry.client.facade.CloudControllerClientImpl.getApplications(CloudControllerClientImpl.java:265)
	at org.example.Main.main(Main.java:53)

```

Thank you <3

**Comment by theghost5800** [comment]
HI @vah13 , I have a look at the sample code which is outdated. For some methods you can use the client without specifying organization and space but for methods like getApplications you need to initialize the client with organization and space. 
Keep in mind that this client is not the official cloudfoundry [cf-java-client](https://github.com/cloudfoundry/cf-java-client), this is only a facade which use cf-java-client.

**Comment by vah13** [comment]
Ah, got it, so after creating a client and extracting spaces, I should define a new client for the space using the following constructor, am I right? 

`public CloudControllerClientImpl(URL controllerUrl, CloudCredentials credentials, CloudSpace target, boolean trustSelfSignedCerts)`

Yes, I read that it's a wrapper for the official CF java client, I found this repo more useful than the official :D

**Comment by theghost5800** [comment]
Yes, you need to create a new client for new target org and space. If you are interested how we are using the client, you can take a look at our other open source project [multiapps-controller](https://github.com/cloudfoundry/multiapps-controller).
 Multiapps-controller project is related with MTA Deployment Service and performs mta deployments in CloudFoundry environment.

**Comment by vah13** [comment]
Fine, Thank you. 
And another question, it's not related to the issue, but it's for the lib. Is it possible to get information about `Resource Provider`? I have tried to get more information about the API of the RP but didn't found. 

Thank you

**Comment by theghost5800** [comment]
Sorry but I couldn't understand what is Resource Provider? We don't have such class in the lib. Could you please give more details?

**Comment by vah13** [comment]
![image](https://user-images.githubusercontent.com/7976421/202516553-87efd905-89ba-4575-9af8-7e77a9788303.png)

![image](https://user-images.githubusercontent.com/7976421/202516522-f55b3cf7-96f6-44d9-af38-ca66f290fc68.png)

**Comment by vah13** [comment]
![image](https://user-images.githubusercontent.com/7976421/202516611-8a922db1-cc4d-4415-9918-e65657c49c5a.png)
![image](https://user-images.githubusercontent.com/7976421/202516710-e76c0486-6826-43b4-a255-dfa50e58b5ad.png)

**Comment by theghost5800** [comment]
This screenshots now give me more context. This api is not related at all with CloudFoundry and you won't find anything related with such ResourceProvider in cf-java-client. Even console cli is different than cf cli.
CF java client is more similar to cf cli(written in go) and interact with the following rest apis - http://v3-apidocs.cloudfoundry.org/version/3.128.0/index.html#resources

Unfortunately you have to look for different library to get information about Resource Provider.

**Comment by vah13** [comment]
Thank you
